spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apt_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_google_client_id
            client-secret: your_google_client_secret
            scope:
              - email
              - profile
          naver:
            client-id: your_naver_client_id
            client-secret: your_naver_client_secret